"""
    Top level server code.

    ------------------

    Will use a dictionary to store the DNS data.
        - The dictionary will be formatted in the following way:
            - key : hostname (the url)
            - value: tuple -> (ip address, A/NS)
    
    ----------------

    The rs code will be organized several methods and the main section that calls the methods. The methods are:
        - getDNSEntries
        - processDNSQuery (check if hostname exists in the server dictionary)
        - server
"""

import os
import socket
import threading
import time
import sys

ROOT_SERVER = "RootServer"
MAX_REQUEST_SIZE = 200
TS_BIND_ADDRESS = ''
ERROR_MESSAGE = '- Error:HOST NOT FOUND'

def getDNSEntries(filePath = "./PROJ2-DNSTS1.txt"):
    r"""
        Will read the "PROJI-DNSRS.txt" file to obtain the DNS entries to be stored for the 
        server. Will go through each line and put the entries in a dictionary as described above.
        Will return the dictionary as a result.

        ---------------

        @params:
            - filePath : path to the file; default set to given input in the same directory

        ----------------

        @return:
            dict : ip address and flag as value with hostname as key
    """
    
    #initiate the dictionary:
    dnsEntryDict = {}

    #read file and populate dictionary
    with open(filePath,mode='r') as entryFile:
        for entryLine in entryFile.readlines():
            entryComponents = entryLine.split()
            hostName = entryComponents[0].lower()
            address = entryComponents[1]
            flag = entryComponents[2]
            dnsEntryDict[hostName]  = (address,flag)   
    return dnsEntryDict

def processDNSQuery(queriedHostname,dnsDict):
    r"""
        Searches the dns dictionary for the queried hostname. If it exists then it returns the
        address and flag associated with it in the dictionary. 
        
        --------------------

        @param:
            
            queriedHostname : the hostname to be looked up, supplied by the client
            dnsDict : data structure holding the dns mappings; generated by getDNSEntries()
        
        --------------------

        @return:
            
            str :  the address and flag associated with the provided hostname if it exists. If it does not then the error message will be displayed.
        
        ---------------------

        Uses the get() method of the dns dictionary where if the key does not exist then the 
        error message will be returned. The key of the dictionary will be the host name/
        domain name.
    """
    
    #get the (hostname,flag) tuple that will be the response to the client request; dnsDict.get(queriedHostname,dnsDict.get(TOP_LEVEL_SERVER)) ;getItemFromDict(queriedHostname,dnsDict)
    queryResponseEntry = dnsDict.get(queriedHostname,None)

    # turn the response entry to a string (so it can be sent back through socket stream)
    toBeReturned = ''
    if queryResponseEntry is not None:
        toBeReturned = queryResponseEntry[0] + " " + queryResponseEntry[1]
    else:
        toBeReturned = ERROR_MESSAGE

    return toBeReturned

def server(tsPort):
    r"""
        Method to set up server and keep it running. Based on project zero code.

        ---------------------

        @param:
            tsPort : the port to bind the ts; obtained originally from the command line
        
        ---------------------

        Will receive requests from the client and check the dns dictionary 
        (which will be set up at the start of this method) to see if the hostname
        exists. If it does then its corresponding details will be returned, if not then
        the error message will be returned.

        ------------------------

        For now will bind server to localhost and test on same machine for all scripts.
        Will change this later to include capabilities to run on multiple machines.
    """

    
    # set the host address or port based on project requirements here
    hostAddress = TS_BIND_ADDRESS
    hostPort = tsPort

    #setup dns data structure:
    dnsDict = getDNSEntries()

    #create the server socket and initiate it:
    try:
        serverSocket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
    except:
        exit()
    
    serverBindingDetails = (hostAddress,hostPort)
    serverSocket.bind(serverBindingDetails)
    serverSocket.listen(1) #in python 2.7 you need to have 1

    #wait for client request and process the request:
    clientSocketId, clientAddress = serverSocket.accept()

    # loop so that multiple requests can be received:
    while(1):
        try:

            #   extract data from client socket:
            clientDataReceived_bytes = clientSocketId.recv(MAX_REQUEST_SIZE)
            clientDataReceived = clientDataReceived_bytes.decode('utf-8').strip()

            #   check if hostname is in the toplevel dns server:
            toBeSentBackToClient = processDNSQuery(clientDataReceived,dnsDict)

            #   return the results to the client:
            clientSocketId.send(toBeSentBackToClient.encode('utf-8'))
        except:
            break
    

    serverSocket.close()
    exit()

if __name__ == "__main__":

    #get command line argument for the port
    tsPort = int(sys.argv[1])

    serverThread = threading.Thread(name='serverThread',target=server,args=[tsPort])
    serverThread.start()
    print("Server Thread Started")